[package]
name = "quick-retire"
version = "0.2.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.103"
ilhook = { version = "2.3.0", default-features = false, features = ["x86"] }
bunny-plugin = { git = "https://github.com/Relial/bunny-plugin.git", tag = "api-v3", features = ["serde"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.2"
windows = { version = "0.*", features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
    "Win32_System_LibraryLoader",
] }
mhfz-structs = { git = "https://github.com/Relial/mhfz-structs.git", rev = "6a63007c8399eabab59089a3b10ae22f6cde7c06" }
